### ISSUE TITLE
Create roadmap for the career transition and beyond

### ISSUE THREAD

**Issue by ryu-hg** [ryu-hg/ba-job-search#3]
## User Story
As a career transitioner, I want to create a roadmap for my job search so that I can visualize and plan my career transition strategy.

## Description
Viewing the candidate as a product, create a visual representation similar to product roadmap to plan tasks necessary to achieve transition into a business analysis focused role, and upskilling journey beyond that.

Tasks mapped on the roadmap should include but not limited to;
- Actual job search and application processes.
- Studying and certification efforts.
- Building the portfolio.
- Any time-constrained events that contribute to the career transition.
- Future upskilling goals beyond the career transition.

Use visual collaboration tools like Visio, Lucidchart, and Miro to generate it.

## Dependencies
In order to build the roadmap, all key tasks must be outlined as well. Tasks are currently managed as [GitHub Issues](https://github.com/ryu-hg/ba-job-search/issues), and I should be able to map most of these tasks directly onto the roadmap.

## Acceptance Criteria
- [x] A roadmap for the job search journey.
- [x] Covers all tasks related to the career transition effort.
- [ ] Covers future upskilling goals.

## Priority
Medium

## Estimated Effort
Low
